// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGn_WASuQjvZDGeKQvoWQqK6NRtXC58VQ',
    appId: '1:729507431207:web:9ba873e2bbae3dc48e1f02',
    messagingSenderId: '729507431207',
    projectId: 'food-delivery-11c57',
    authDomain: 'food-delivery-11c57.firebaseapp.com',
    storageBucket: 'food-delivery-11c57.firebasestorage.app',
    measurementId: 'G-02MXT5H14N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQXgXTCeXJP7j-Kr0-2kx5Z-0w_XKMzoE',
    appId: '1:729507431207:android:77a82f276c58730a8e1f02',
    messagingSenderId: '729507431207',
    projectId: 'food-delivery-11c57',
    storageBucket: 'food-delivery-11c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBthU9C5V2KpXw8kw5EUgKDhGB5rYVzbEw',
    appId: '1:729507431207:ios:954543f29e258d328e1f02',
    messagingSenderId: '729507431207',
    projectId: 'food-delivery-11c57',
    storageBucket: 'food-delivery-11c57.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBthU9C5V2KpXw8kw5EUgKDhGB5rYVzbEw',
    appId: '1:729507431207:ios:954543f29e258d328e1f02',
    messagingSenderId: '729507431207',
    projectId: 'food-delivery-11c57',
    storageBucket: 'food-delivery-11c57.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGn_WASuQjvZDGeKQvoWQqK6NRtXC58VQ',
    appId: '1:729507431207:web:844bbd69b97c4cd98e1f02',
    messagingSenderId: '729507431207',
    projectId: 'food-delivery-11c57',
    authDomain: 'food-delivery-11c57.firebaseapp.com',
    storageBucket: 'food-delivery-11c57.firebasestorage.app',
    measurementId: 'G-MZX9V148PS',
  );
}
